### ISSUE TITLE
In the example given, content:encoded should not enclose DOCTYPE/HTML/BODY tags

### ISSUE THREAD

**Issue by jamescridland** [theDanielJLewis/podcast-test-feed#3]
The specification is here:
http://www.rssboard.org/rss-profile#namespace-elements-content-encoded

This is expected to be HTML markup: you shouldn't put <HTML>, <BODY> or <DOCTYPE> declarations in here.

**Comment by theDanielJLewis** [comment]
I'm going to close this for now as _The Audacity to Podcast's_ feed (from PowerPress via Podcast Mirror) is a reference for future use, but not intended as an example of usage.
